/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestioncarreras.GUI;

import gestioncarreras.GUI.Principal;
import gestioncarreras.objetos.Carrera;
import gestioncarreras.objetos.Corredor;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author alvar
 */
public class AltaCarrera extends javax.swing.JDialog {
    private Principal principal;
    DefaultListModel<Corredor> lista;
    
    public Corredor corredor=new Corredor("Verstappen","71798717Y",new Date(1997),"Bélgica",654321098);
    public Corredor corredor2=new Corredor("Leclerc","717987654S",new Date(1997),"Mónaco",693528741);

    /**
     * Creates new form AltaCarrera
     */
    public AltaCarrera(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        principal=(Principal)parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAltaCarrera = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelFechaCarr = new javax.swing.JLabel();
        jDateChooserFechaCarr = new com.toedter.calendar.JDateChooser();
        jLabelLugar = new javax.swing.JLabel();
        jTextFieldLugar = new javax.swing.JTextField();
        jLabelParticipantes = new javax.swing.JLabel();
        jTextFieldParticipantes = new javax.swing.JTextField();
        jLabelLista = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListParticipantes = new javax.swing.JList<>();
        jButtonAltaCarr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelAltaCarrera.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelAltaCarrera.setText("Alta Carrera");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Nombre:");

        jTextFieldNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabelFechaCarr.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelFechaCarr.setText("Fecha Carrera:");

        jLabelLugar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelLugar.setText("Lugar Carrera:");

        jTextFieldLugar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabelParticipantes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelParticipantes.setText("Nº Participantes:");

        jTextFieldParticipantes.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabelLista.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelLista.setText("Lista Participantes:");

        jScrollPane1.setViewportView(jListParticipantes);

        jButtonAltaCarr.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonAltaCarr.setText("ALTA");
        jButtonAltaCarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaCarrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabelAltaCarrera)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFechaCarr)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldLugar)
                            .addComponent(jDateChooserFechaCarr, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombre))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelLista)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelParticipantes)
                                    .addComponent(jLabelLugar))
                                .addGap(34, 34, 34)
                                .addComponent(jTextFieldParticipantes)))
                        .addGap(52, 52, 52))))
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jButtonAltaCarr, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabelAltaCarrera)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelFechaCarr)
                    .addComponent(jDateChooserFechaCarr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLugar)
                    .addComponent(jTextFieldLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelParticipantes)
                    .addComponent(jTextFieldParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLista)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jButtonAltaCarr, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAltaCarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaCarrActionPerformed
        // TODO add your handling code here:
        String nombre=jTextFieldNombre.getText();
        Date fechaCarr=jDateChooserFechaCarr.getDate();
        String lugar=jTextFieldLugar.getText();
        Integer nParticipantes=java.lang.Integer.parseInt(jTextFieldParticipantes.getText());
        
        Carrera carrera=new Carrera(nombre,fechaCarr,lugar,nParticipantes,null);
        principal.aniadirCarrera(carrera);
        dispose();
        
    }//GEN-LAST:event_jButtonAltaCarrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AltaCarrera dialog = new AltaCarrera(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAltaCarr;
    private com.toedter.calendar.JDateChooser jDateChooserFechaCarr;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAltaCarrera;
    private javax.swing.JLabel jLabelFechaCarr;
    private javax.swing.JLabel jLabelLista;
    private javax.swing.JLabel jLabelLugar;
    private javax.swing.JLabel jLabelParticipantes;
    private javax.swing.JList<Corredor> jListParticipantes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldLugar;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldParticipantes;
    // End of variables declaration//GEN-END:variables
}
